global_frame: odom

rolling_window: true
publish_frequency: 2.0

inflater:
  robot_radius: 0.30 # default 0.30 # TODO: isn't this redundant?
  inflation_radius: 0.30 # default 0.70
  cost_scaling_factor: 5.0 # default 10.0

# size of costmap is specified below
width: 4.0
height: 4.0
resolution: 0.025

# plugins for local costmap are below
plugins:
 - {name: obstacles, type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,  type: "costmap_2d::InflationLayer"}

obstacles:
  publish_observations: false


