global_frame: map

update_frequency: 5.0
publish_frequency: 0.0
static_map: true

inflater:
  robot_radius: 0.30 # default 0.30 # TODO: isn't this redundant?
  inflation_radius: 0.30 # default 0.70
  cost_scaling_factor: 5.0 # default 10.0

# plugins for global costmap are below
plugins:
 - {name: static_map, type: "costmap_2d::StaticLayer"}
 - {name: obstacles,  type: "costmap_2d::FetchDepthLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}

