# Planner selection
base_global_planner: "navfn/NavfnROS" # default
# base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

# Recovery behaviors are defined below
# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
  - name: "aggressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 3.0
rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017
aggressive_reset: 
  reset_distance: 0.5

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 5.0

GlobalPlanner: # for defaults see http://wiki.ros.org/global_planner
  allow_unknown: true
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1
  outline_map: true

NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 25.0
controller_patience: 15.0



TrajectoryPlannerROS:
  # base vel/accel profile is in robot folders
  # tolerances (defaults)
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  # forward simulation
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 10
  # scoring (defaults)
  meter_scoring: true
  path_distance_bias: 0.5
  goal_distance_bias: 0.75
  occdist_scale: 0.00625
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true
  dwa: false
  # other
  oscillation_reset_dist: 0.05
  # debug
  publish_cost_grid_pc: false
  # Fetch Specifics
  acc_lim_x: 0.35
  acc_lim_y: 0.0
  acc_lim_theta: 0.8
  max_vel_x: 1.0
  min_vel_x: 0.15
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.3
  holonomic_robot: false
